import { createContext, useContext, useState } from "react";

const translations = {
  en: {
    // Navbar
    "nav.navigation": "Navigation",
    "nav.allSystemsOk": "All Systems Operational",
    "nav.notifications": "Notifications",
    "nav.markAllRead": "Mark all read",
    "nav.viewAll": "View all notifications",
    "nav.proExporter": "Pro Exporter",
    "nav.logout": "Logout",
    "nav.viewProfile": "View Profile",
    "nav.exportProgress": "Export Progress",
    "nav.myDocuments": "My Documents",
    "nav.accountSettings": "Account Settings",

    // Sidebar nav labels
    "nav.dashboard": "Dashboard",
    "nav.addProduct": "Add Product",
    "nav.marketAnalysis": "Market Analysis",
    "nav.profitSimulator": "Profit Simulator",
    "nav.marketplace": "Marketplace",
    "nav.exportPlan": "Export Plan",
    "nav.compliance": "Compliance",
    "nav.readinessScore": "Readiness Score",
    "nav.reports": "Reports",
    "nav.documents": "Documents",
    "nav.aiAdvisor": "AI Advisor",
    "nav.settings": "Settings",

    // Dashboard
    "dash.heroSub": "AI-powered export intelligence for Indian MSMEs. Analyze markets, simulate profits, ensure compliance — all in one platform.",
    "dash.liveOpportunities": "Live Export Opportunities",
    "dash.welcomeTitle": "Welcome to ExportReady",
    "dash.productsListed": "Products Listed",
    "dash.marketsAnalyzed": "Markets Analyzed",
    "dash.documentsReady": "Documents Ready",
    "dash.potentialRevenue": "Potential Revenue",
    "dash.topMarket": "Top Market",
    "dash.readinessScore": "Readiness Score",
    "dash.exportVolumeChart": "India Export Volume by Market",
    "dash.exportMixChart": "Export Mix by Sector",
    "dash.quickAnalysis": "Quick Product Analysis",
    "dash.productPlaceholder": "Enter product (e.g., Premium Cotton Shirts, Basmati Rice, Spices)",
    "dash.analyze": "Analyze",
    "dash.analyzing": "Analyzing...",
    "dash.clickToImprove": "Click to improve",
    "dash.nav.registerProducts": "Register products for export",
    "dash.nav.marketIntelligence": "AI-powered global market intelligence",
    "dash.nav.profitSim": "Simulate FOB pricing & profitability",
    "dash.nav.exportPlanDesc": "Timeline, schemes & compliance roadmap",
    "dash.nav.complianceDesc": "Rule-by-rule export compliance analysis",
    "dash.nav.readinessDesc": "Track your export readiness progress",
    "dash.alertProductRequired": "Please enter a product name",
    "dash.errorGeneric": "Something went wrong",
    "dash.exportVolumeDataset": "India Export Volume (₹ Crore)",
    "dash.sectorAgricultural": "Agricultural",
    "dash.sectorTextiles": "Textiles",
    "dash.sectorElectronics": "Electronics",
    "dash.sectorPharma": "Pharma",
    "dash.sectorEngineering": "Engineering",
    "dash.demandUp": "Demand ↑",
    "dash.live": "Live",
    "dash.indiaRiceExports": "India Rice (HS 1006) Annual Exports",
    "dash.realTime": "Real-time",
    "dash.estimated": "Estimated",
    "dash.marketAnalysisBased": "Based on market analysis",
    "dash.demandIndex": "Demand index",
    "dash.topExportMarkets": "Top Export Markets",
    "dash.opportunityScores": "Opportunity Scores",
    "dash.scoreLabel": "Score",
    "dash.requiredDocuments": "Required Documents",
    "dash.potentialBuyers": "Potential Buyers",
    "dash.estimatedProfit": "Estimated Profit",
    "dash.impactTitle": "ExportReady Impact",
    "dash.impactSubtitle": "Why this platform matters for Indian MSMEs",
    "dash.impactStat1": "63 Million",
    "dash.impactDesc1": "MSMEs in India eligible to export",
    "dash.impactStat2": "Only 1.8%",
    "dash.impactDesc2": "Actually export today — massive opportunity",
    "dash.impactStat3": "₹4.2L/year",
    "dash.impactDesc3": "Average MSME loss due to wrong HS Codes",
    "dash.impactStat4": "70% fewer",
    "dash.impactDesc4": "Compliance errors with ExportReady",
    "dash.footer": "Enterprise-Grade Security · Global Compliance · Real-Time AI Analytics · Data: UN Comtrade 2023",

    // ExportReadiness
    "readiness.title": "Export Readiness Score",
    "readiness.stepsComplete": "{completed} of {total} steps complete",
    "readiness.nextStep": "Next Required Step",
    "readiness.step": "Step",
    "readiness.whyMatters": "Why this matters:",
    "readiness.markDone": "Mark Done",
    "readiness.ready": "Ready",
    "readiness.markComplete": "Mark as complete",
    "readiness.markIncomplete": "Mark as incomplete",
    "readiness.completed": "Completed",
    "readiness.points": "pts",
    "readiness.allComplete": "All Steps Complete!",
    "readiness.allCompleteDesc": "Your export journey is fully set up.",
    "readiness.journeyTitle": "Export Journey — 5 Steps to Your First Shipment",
    "readiness.undo": "Undo",
    "readiness.auditTitle": "Detailed Compliance Audit",
    "readiness.completeTo": "Complete these to reach",
    "readiness.level.exportReady": "Export Ready ✓",
    "readiness.level.almostReady": "Almost Ready",
    "readiness.level.gettingStarted": "Getting Started",
    "readiness.level.justBeginning": "Just Beginning",
    "readiness.journey.iec.label": "Upload IEC Certificate",
    "readiness.journey.iec.why": "IEC (Import Export Code) is mandatory to legally export products from India. Issued by DGFT.",
    "readiness.journey.iec.action": "Upload Certificate",
    "readiness.journey.product.label": "Add Product Details",
    "readiness.journey.product.why": "List your product with HS code, specifications, and pricing to begin the export process.",
    "readiness.journey.product.action": "Add Product",
    "readiness.journey.compliance.label": "Run Compliance Check",
    "readiness.journey.compliance.why": "Verify regulatory requirements, certifications, and labeling rules for your target market.",
    "readiness.journey.compliance.action": "Check Compliance",
    "readiness.journey.market.label": "Select Target Market",
    "readiness.journey.market.why": "Use AI insights to identify the best export destinations and buyer demand for your product.",
    "readiness.journey.market.action": "Explore Markets",
    "readiness.journey.profit.label": "Calculate Export Profit",
    "readiness.journey.profit.why": "Simulate your FOB pricing, customs duties, margins, and overall profit potential.",
    "readiness.journey.profit.action": "Simulate Profit",
    "readiness.audit.iec.label": "IEC Registration",
    "readiness.audit.iec.detail": "Import Export Code from DGFT portal",
    "readiness.audit.product.label": "Product Listed on Platform",
    "readiness.audit.product.detail": "At least one product configured",
    "readiness.audit.apeda.label": "APEDA / RCMC Registration",
    "readiness.audit.apeda.detail": "Required for agricultural & processed food exports",
    "readiness.audit.quality.label": "Quality Certification",
    "readiness.audit.quality.detail": "BIS / ISO / FSSAI / WHO-GMP as applicable",
    "readiness.audit.buyers.label": "Buyer Contacts Identified",
    "readiness.audit.buyers.detail": "At least 3 verified international buyers",
    "readiness.audit.bank.label": "Export Bank Account (EEFC)",
    "readiness.audit.bank.detail": "Exchange Earners Foreign Currency account",

    // Profile
    "profile.exportPassport": "Export Passport",
    "profile.profileComplete": "Profile Complete",
    "profile.businessDetails": "Business Details",
    "profile.edit": "Edit",
    "profile.save": "Save",
    "profile.cancel": "Cancel",
    "profile.experienceLevel": "Export Experience Level",
    "profile.readinessProgress": "Readiness Score Progress",
    "profile.exportProducts": "Export Products",
    "profile.addProduct": "+ Add Product",
    "profile.targetCountries": "Target Countries",
    "profile.exploreMore": "Explore More →",
    "profile.viewReadiness": "View Readiness →",
    "profile.since": "Since",
    "profile.beginner": "Beginner",
    "profile.active": "Active",
    "profile.pro": "Pro",
    "profile.beginnerDesc": "New to exporting",
    "profile.activeDesc": "1–3 shipments/year",
    "profile.proDesc": "Regular exporter, established ops",
    "profile.current": "Current",
    "profile.demandIndex": "Demand index",
      "profile.exporter": "ஏற்றுமதியாளர்",
      "profile.iec": "IEC",
      "profile.gst": "GST",
      "profile.type": "வகை",
      "profile.exportingSince": "இருந்து ஏற்றுமதி",
      "profile.notSet": "அமைக்கப்படவில்லை",
      "profile.company": "நிறுவனம்",
      "profile.businessType": "வணிக வகை",
      "profile.city": "நகரம்",
      "profile.state": "மாநிலம்",
      "profile.iecNumber": "IEC எண்",
      "profile.gstNumber": "GST எண்",
      "profile.email": "மின்னஞ்சல்",
      "profile.phone": "தொலைபேசி",
      "profile.website": "இணையதளம்",
      "profile.hsCode": "HS குறியீடு",
      "profile.statusActive": "செயலில்",
      "profile.statusDraft": "வரைவு",
    "profile.exporter": "Exporter",
    "profile.iec": "IEC",
    "profile.gst": "GST",
    "profile.type": "Type",
    "profile.exportingSince": "Exporting since",
    "profile.notSet": "Not set",
    "profile.company": "Company",
    "profile.businessType": "Business Type",
    "profile.city": "City",
    "profile.state": "State",
    "profile.iecNumber": "IEC Number",
    "profile.gstNumber": "GST Number",
    "profile.email": "Email",
    "profile.phone": "Phone",
    "profile.website": "Website",
    "profile.hsCode": "HS Code",
    "profile.statusActive": "Active",
    "profile.statusDraft": "Draft",

    // AccountSettings
    "settings.title": "Account Settings",
    "settings.subtitle": "Notifications, integrations, and preferences.",
    "settings.saveChanges": "Save Changes",
    "settings.saved": "Saved",
    "settings.notifPrefs": "Notification Preferences",
    "settings.notifPrefsDesc": "Choose which email alerts matter to your export operations.",
    "settings.complianceDeadlines": "Compliance Deadlines",
    "settings.complianceDeadlinesSub": "IEC renewal, RCMC expiry, FSSAI alerts",
    "settings.marketAlerts": "Market Opportunity Alerts",
    "settings.marketAlertsSub": "Demand spikes, tariff changes in target markets",
    "settings.docReadiness": "Document Readiness",
    "settings.docReadinessSub": "When generated docs are ready to download",
    "settings.weeklyDigest": "Weekly Digest",
    "settings.weeklyDigestSub": "Summary of your export readiness & activity",
    "settings.langCurrency": "Language & Currency",
    "settings.langCurrencyDesc": "Display preferences for your region.",
    "settings.language": "Language",
    "settings.currency": "Currency",
    "settings.timezone": "Timezone",
    "settings.dataPrivacy": "Data & Privacy",
    "settings.exportData": "Export My Data",
    "settings.integrations": "Connected Integrations",
    "settings.integrationsDesc": "Link your government portals and logistics partners for automated sync.",
    "settings.connect": "Connect",
    "settings.disconnect": "Disconnect",
    "settings.plan": "Subscription Plan",
    "settings.planDesc": "Manage your ExportReady plan.",
    "settings.currentPlan": "Current Plan",
    "settings.includedFeatures": "Included Features",
    "settings.upgradePlan": "Upgrade Plan",
    "settings.viewInvoices": "View Invoices",
    "settings.cancelPlan": "Cancel Plan",
  },

  hi: {
    // Navbar
    "nav.navigation": "नेविगेशन",
    "nav.allSystemsOk": "सभी सिस्टम सामान्य",
    "nav.notifications": "सूचनाएं",
    "nav.markAllRead": "सभी पढ़ी हुई मार्क करें",
    "nav.viewAll": "सभी सूचनाएं देखें",
    "nav.proExporter": "प्रो निर्यातक",
    "nav.logout": "लॉग आउट",
    "nav.viewProfile": "प्रोफ़ाइल देखें",
    "nav.exportProgress": "निर्यात प्रगति",
    "nav.myDocuments": "मेरे दस्तावेज़",
    "nav.accountSettings": "खाता सेटिंग",

    // Sidebar
    "nav.dashboard": "डैशबोर्ड",
    "nav.addProduct": "उत्पाद जोड़ें",
    "nav.marketAnalysis": "बाज़ार विश्लेषण",
    "nav.profitSimulator": "लाभ सिम्युलेटर",
    "nav.marketplace": "मार्केटप्लेस",
    "nav.exportPlan": "निर्यात योजना",
    "nav.compliance": "अनुपालन",
    "nav.readinessScore": "तैयारी स्कोर",
    "nav.reports": "रिपोर्ट",
    "nav.documents": "दस्तावेज़",
    "nav.aiAdvisor": "AI सलाहकार",
    "nav.settings": "सेटिंग",

    // Dashboard
    "dash.heroSub": "भारतीय MSMEs के लिए AI-संचालित निर्यात समाधान। बाज़ार विश्लेषण, लाभ सिमुलेशन और अनुपालन — एक ही प्लेटफ़ॉर्म पर।",
    "dash.liveOpportunities": "लाइव निर्यात अवसर",
    "dash.welcomeTitle": "ExportReady में आपका स्वागत है",
    "dash.productsListed": "सूचीबद्ध उत्पाद",
    "dash.marketsAnalyzed": "विश्लेषित बाज़ार",
    "dash.documentsReady": "तैयार दस्तावेज़",
    "dash.potentialRevenue": "संभावित राजस्व",
    "dash.topMarket": "शीर्ष बाज़ार",
    "dash.readinessScore": "तैयारी स्कोर",
    "dash.exportVolumeChart": "बाज़ार के अनुसार भारत का निर्यात",
    "dash.exportMixChart": "क्षेत्र के अनुसार निर्यात मिश्रण",
    "dash.quickAnalysis": "त्वरित उत्पाद विश्लेषण",
    "dash.productPlaceholder": "उत्पाद दर्ज करें (जैसे, कपास शर्ट, बासमती चावल, मसाले)",
    "dash.analyze": "विश्लेषण करें",
    "dash.analyzing": "विश्लेषण हो रहा है...",
    "dash.clickToImprove": "सुधार के लिए क्लिक करें",
    "dash.nav.registerProducts": "निर्यात के लिए उत्पाद पंजीकृत करें",
    "dash.nav.marketIntelligence": "AI-संचालित वैश्विक बाज़ार इंटेलिजेंस",
    "dash.nav.profitSim": "FOB मूल्य निर्धारण और लाभ का सिमुलेशन",
    "dash.nav.exportPlanDesc": "टाइमलाइन, योजनाएं और अनुपालन रोडमैप",
    "dash.nav.complianceDesc": "नियम-दर-नियम निर्यात अनुपालन विश्लेषण",
    "dash.nav.readinessDesc": "आपकी तैयारी प्रगति ट्रैक करें",
    "dash.alertProductRequired": "कृपया उत्पाद नाम दर्ज करें",
    "dash.errorGeneric": "कुछ गलत हो गया",
    "dash.exportVolumeDataset": "भारत का निर्यात वॉल्यूम (₹ करोड़)",
    "dash.sectorAgricultural": "कृषि",
    "dash.sectorTextiles": "कपड़ा",
    "dash.sectorElectronics": "इलेक्ट्रॉनिक्स",
    "dash.sectorPharma": "फार्मा",
    "dash.sectorEngineering": "इंजीनियरिंग",
    "dash.demandUp": "मांग ↑",
    "dash.live": "लाइव",
    "dash.indiaRiceExports": "भारत चावल (HS 1006) वार्षिक निर्यात",
    "dash.realTime": "रीयल-टाइम",
    "dash.estimated": "अनुमानित",
    "dash.marketAnalysisBased": "बाज़ार विश्लेषण पर आधारित",
    "dash.demandIndex": "मांग सूचकांक",
    "dash.topExportMarkets": "शीर्ष निर्यात बाज़ार",
    "dash.opportunityScores": "अवसर स्कोर",
    "dash.scoreLabel": "स्कोर",
    "dash.requiredDocuments": "आवश्यक दस्तावेज़",
    "dash.potentialBuyers": "संभावित खरीदार",
    "dash.estimatedProfit": "अनुमानित लाभ",
    "dash.impactTitle": "ExportReady प्रभाव",
    "dash.impactSubtitle": "भारतीय MSMEs के लिए यह प्लेटफ़ॉर्म क्यों महत्वपूर्ण है",
    "dash.impactStat1": "63 मिलियन",
    "dash.impactDesc1": "भारत में निर्यात के लिए पात्र MSMEs",
    "dash.impactStat2": "केवल 1.8%",
    "dash.impactDesc2": "आज वास्तव में निर्यात करते हैं — बड़ा अवसर",
    "dash.impactStat3": "₹4.2L/वर्ष",
    "dash.impactDesc3": "गलत HS कोड के कारण औसत MSME नुकसान",
    "dash.impactStat4": "70% कम",
    "dash.impactDesc4": "ExportReady के साथ अनुपालन त्रुटियां",
    "dash.footer": "एंटरप्राइज़-ग्रेड सुरक्षा · वैश्विक अनुपालन · रीयल-टाइम AI एनालिटिक्स · डेटा: UN Comtrade 2023",

    // ExportReadiness
    "readiness.title": "निर्यात तैयारी स्कोर",
    "readiness.stepsComplete": "{completed} में से {total} चरण पूरे",
    "readiness.nextStep": "अगला आवश्यक चरण",
    "readiness.step": "चरण",
    "readiness.whyMatters": "यह क्यों ज़रूरी है:",
    "readiness.markDone": "पूर्ण मार्क करें",
    "readiness.ready": "तैयार",
    "readiness.markComplete": "पूर्ण के रूप में चिह्नित करें",
    "readiness.markIncomplete": "अपूर्ण के रूप में चिह्नित करें",
    "readiness.completed": "पूर्ण",
    "readiness.points": "अंक",
    "readiness.allComplete": "सभी चरण पूर्ण!",
    "readiness.allCompleteDesc": "आपकी निर्यात यात्रा पूरी तरह सेट है।",
    "readiness.journeyTitle": "निर्यात यात्रा — पहले शिपमेंट के लिए 5 चरण",
    "readiness.undo": "पूर्ववत करें",
    "readiness.auditTitle": "विस्तृत अनुपालन ऑडिट",
    "readiness.completeTo": "इन्हें पूरा करके पहुंचें",
    "readiness.level.exportReady": "निर्यात के लिए तैयार ✓",
    "readiness.level.almostReady": "लगभग तैयार",
    "readiness.level.gettingStarted": "शुरुआत",
    "readiness.level.justBeginning": "अभी शुरुआत",
    "readiness.journey.iec.label": "IEC प्रमाणपत्र अपलोड करें",
    "readiness.journey.iec.why": "IEC (इम्पोर्ट एक्सपोर्ट कोड) भारत से कानूनी रूप से निर्यात के लिए अनिवार्य है। DGFT द्वारा जारी।",
    "readiness.journey.iec.action": "प्रमाणपत्र अपलोड करें",
    "readiness.journey.product.label": "उत्पाद विवरण जोड़ें",
    "readiness.journey.product.why": "निर्यात प्रक्रिया शुरू करने के लिए HS कोड, विनिर्देश और मूल्य के साथ उत्पाद सूचीबद्ध करें।",
    "readiness.journey.product.action": "उत्पाद जोड़ें",
    "readiness.journey.compliance.label": "अनुपालन जांच चलाएं",
    "readiness.journey.compliance.why": "लक्ष्य बाज़ार के लिए नियामक आवश्यकताएं, प्रमाणन और लेबलिंग नियम सत्यापित करें।",
    "readiness.journey.compliance.action": "अनुपालन जांचें",
    "readiness.journey.market.label": "लक्ष्य बाज़ार चुनें",
    "readiness.journey.market.why": "AI इनसाइट्स से आपके उत्पाद के लिए सर्वोत्तम निर्यात गंतव्य और खरीदार मांग पहचानें।",
    "readiness.journey.market.action": "बाज़ार खोजें",
    "readiness.journey.profit.label": "निर्यात लाभ गणना",
    "readiness.journey.profit.why": "FOB मूल्य, शुल्क, मार्जिन और कुल लाभ क्षमता का सिमुलेशन करें।",
    "readiness.journey.profit.action": "लाभ सिमुलेट करें",
    "readiness.audit.iec.label": "IEC पंजीकरण",
    "readiness.audit.iec.detail": "DGFT पोर्टल से इम्पोर्ट एक्सपोर्ट कोड",
    "readiness.audit.product.label": "प्लेटफ़ॉर्म पर उत्पाद सूचीबद्ध",
    "readiness.audit.product.detail": "कम से कम एक उत्पाद कॉन्फ़िगर",
    "readiness.audit.apeda.label": "APEDA / RCMC पंजीकरण",
    "readiness.audit.apeda.detail": "कृषि और प्रसंस्कृत खाद्य निर्यात के लिए आवश्यक",
    "readiness.audit.quality.label": "गुणवत्ता प्रमाणन",
    "readiness.audit.quality.detail": "BIS / ISO / FSSAI / WHO-GMP जैसा लागू",
    "readiness.audit.buyers.label": "खरीदार संपर्क पहचाने",
    "readiness.audit.buyers.detail": "कम से कम 3 सत्यापित अंतरराष्ट्रीय खरीदार",
    "readiness.audit.bank.label": "निर्यात बैंक खाता (EEFC)",
    "readiness.audit.bank.detail": "एक्सचेंज अर्नर्स फॉरेन करेंसी खाता",

    // Profile
    "profile.exportPassport": "निर्यात पासपोर्ट",
    "profile.profileComplete": "प्रोफ़ाइल पूर्ण",
    "profile.businessDetails": "व्यापार विवरण",
    "profile.edit": "संपादित करें",
    "profile.save": "सहेजें",
    "profile.cancel": "रद्द करें",
    "profile.experienceLevel": "निर्यात अनुभव स्तर",
    "profile.readinessProgress": "तैयारी स्कोर प्रगति",
    "profile.exportProducts": "निर्यात उत्पाद",
    "profile.addProduct": "+ उत्पाद जोड़ें",
    "profile.targetCountries": "लक्षित देश",
    "profile.exploreMore": "और देखें →",
    "profile.viewReadiness": "तैयारी देखें →",
    "profile.since": "से",
    "profile.beginner": "शुरुआती",
    "profile.active": "सक्रिय",
    "profile.pro": "प्रो",
    "profile.beginnerDesc": "निर्यात में नए",
    "profile.activeDesc": "1–3 शिपमेंट/वर्ष",
    "profile.proDesc": "नियमित निर्यातक",
    "profile.current": "वर्तमान",
    "profile.demandIndex": "मांग सूचकांक",
    "profile.exporter": "निर्यातक",
    "profile.iec": "IEC",
    "profile.gst": "GST",
    "profile.type": "प्रकार",
    "profile.exportingSince": "से निर्यात",
    "profile.notSet": "सेट नहीं",
    "profile.company": "कंपनी",
    "profile.businessType": "व्यवसाय प्रकार",
    "profile.city": "शहर",
    "profile.state": "राज्य",
    "profile.iecNumber": "IEC नंबर",
    "profile.gstNumber": "GST नंबर",
    "profile.email": "ईमेल",
    "profile.phone": "फोन",
    "profile.website": "वेबसाइट",
    "profile.hsCode": "HS कोड",
    "profile.statusActive": "सक्रिय",
    "profile.statusDraft": "ड्राफ्ट",

    // AccountSettings
    "settings.title": "खाता सेटिंग",
    "settings.subtitle": "सूचनाएं, एकीकरण और प्राथमिकताएं।",
    "settings.saveChanges": "परिवर्तन सहेजें",
    "settings.saved": "सहेजा गया",
    "settings.notifPrefs": "सूचना प्राथमिकताएं",
    "settings.notifPrefsDesc": "चुनें कि कौन से ईमेल अलर्ट आपके लिए महत्वपूर्ण हैं।",
    "settings.complianceDeadlines": "अनुपालन समयसीमाएं",
    "settings.complianceDeadlinesSub": "IEC नवीनीकरण, RCMC समाप्ति, FSSAI अलर्ट",
    "settings.marketAlerts": "बाज़ार अवसर अलर्ट",
    "settings.marketAlertsSub": "मांग में वृद्धि, लक्षित बाज़ारों में टैरिफ परिवर्तन",
    "settings.docReadiness": "दस्तावेज़ तैयारी",
    "settings.docReadinessSub": "जब दस्तावेज़ डाउनलोड के लिए तैयार हों",
    "settings.weeklyDigest": "साप्ताहिक सारांश",
    "settings.weeklyDigestSub": "आपकी निर्यात तैयारी और गतिविधि का सारांश",
    "settings.langCurrency": "भाषा और मुद्रा",
    "settings.langCurrencyDesc": "आपके क्षेत्र के लिए प्रदर्शन प्राथमिकताएं।",
    "settings.language": "भाषा",
    "settings.currency": "मुद्रा",
    "settings.timezone": "समय क्षेत्र",
    "settings.dataPrivacy": "डेटा और गोपनीयता",
    "settings.exportData": "मेरा डेटा निर्यात करें",
    "settings.integrations": "जुड़े हुए एकीकरण",
    "settings.integrationsDesc": "सरकारी पोर्टल और लॉजिस्टिक्स भागीदारों को लिंक करें।",
    "settings.connect": "जोड़ें",
    "settings.disconnect": "हटाएं",
    "settings.plan": "सदस्यता योजना",
    "settings.planDesc": "अपनी ExportReady योजना प्रबंधित करें।",
    "settings.currentPlan": "वर्तमान योजना",
    "settings.includedFeatures": "शामिल सुविधाएं",
    "settings.upgradePlan": "योजना अपग्रेड करें",
    "settings.viewInvoices": "चालान देखें",
    "settings.cancelPlan": "योजना रद्द करें",
  },

  ta: {
    // Navbar
    "nav.navigation": "வழிசெலுத்தல்",
    "nav.allSystemsOk": "அனைத்து அமைப்புகளும் இயங்குகின்றன",
    "nav.notifications": "அறிவிப்புகள்",
    "nav.markAllRead": "அனைத்தையும் படித்ததாகக் குறி",
    "nav.viewAll": "அனைத்து அறிவிப்புகளையும் காண்க",
    "nav.proExporter": "புரொ ஏற்றுமதியாளர்",
    "nav.logout": "வெளியேறு",
    "nav.viewProfile": "சுயவிவரம் காண்க",
    "nav.exportProgress": "ஏற்றுமதி முன்னேற்றம்",
    "nav.myDocuments": "என் ஆவணங்கள்",
    "nav.accountSettings": "கணக்கு அமைப்புகள்",

    // Sidebar
    "nav.dashboard": "டாஷ்போர்டு",
    "nav.addProduct": "பொருள் சேர்க்கவும்",
    "nav.marketAnalysis": "சந்தை பகுப்பாய்வு",
    "nav.profitSimulator": "இலாப சிமுலேட்டர்",
    "nav.marketplace": "சந்தை இடம்",
    "nav.exportPlan": "ஏற்றுமதி திட்டம்",
    "nav.compliance": "இணக்கம்",
    "nav.readinessScore": "தயார்நிலை மதிப்பெண்",
    "nav.reports": "அறிக்கைகள்",
    "nav.documents": "ஆவணங்கள்",
    "nav.aiAdvisor": "AI ஆலோசகர்",
    "nav.settings": "அமைப்புகள்",

    // Dashboard
    "dash.heroSub": "இந்திய MSMEகளுக்கான AI சக்திவாய்ந்த ஏற்றுமதி தளம். சந்தை பகுப்பாய்வு, லாப சிமுலேஷன், இணக்க சரிபார்ப்பு — ஒரே இடத்தில்.",
    "dash.liveOpportunities": "நேரடி ஏற்றுமதி வாய்ப்புகள்",
    "dash.welcomeTitle": "ExportReady-க்கு வரவேற்கிறோம்",
    "dash.productsListed": "பட்டியலிடப்பட்ட பொருட்கள்",
    "dash.marketsAnalyzed": "பகுப்பாய்வு செய்யப்பட்ட சந்தைகள்",
    "dash.documentsReady": "தயாரான ஆவணங்கள்",
    "dash.potentialRevenue": "சாத்தியமான வருவாய்",
    "dash.topMarket": "சிறந்த சந்தை",
    "dash.readinessScore": "தயார்நிலை மதிப்பெண்",
    "dash.exportVolumeChart": "சந்தை வாரியாக இந்தியாவின் ஏற்றுமதி",
    "dash.exportMixChart": "துறை வாரியாக ஏற்றுமதி கலவை",
    "dash.quickAnalysis": "விரைவு பொருள் பகுப்பாய்வு",
    "dash.productPlaceholder": "பொருளை உள்ளிடவும் (எ.கா., பருத்தி சட்டை, பாஸ்மதி அரிசி)",
    "dash.analyze": "பகுப்பாய்வு செய்க",
    "dash.analyzing": "பகுப்பாய்வு நடக்கிறது...",
    "dash.clickToImprove": "மேம்பட கிளிக் செய்க",
    "dash.nav.registerProducts": "ஏற்றுமதிக்காக தயாரிப்புகளை பதிவு செய்யுங்கள்",
    "dash.nav.marketIntelligence": "AI சார்ந்த உலக சந்தை அறிவு",
    "dash.nav.profitSim": "FOB விலை மற்றும் லாபத்தை சிமுலேட் செய்யுங்கள்",
    "dash.nav.exportPlanDesc": "டைம்லைன், திட்டங்கள் & இணக்கம் ரோட்மேப்",
    "dash.nav.complianceDesc": "விதிமுறைகள் அடிப்படையிலான இணக்கம் பகுப்பாய்வு",
    "dash.nav.readinessDesc": "உங்கள் தயார்நிலை முன்னேற்றத்தை கண்காணிக்கவும்",
    "dash.alertProductRequired": "தயாரிப்பு பெயரை உள்ளிடவும்",
    "dash.errorGeneric": "ஏதோ தவறு ஏற்பட்டது",
    "dash.exportVolumeDataset": "இந்திய ஏற்றுமதி அளவு (₹ கோடி)",
    "dash.sectorAgricultural": "விவசாயம்",
    "dash.sectorTextiles": "துணிநூல்",
    "dash.sectorElectronics": "மின்னணு",
    "dash.sectorPharma": "மருந்துகள்",
    "dash.sectorEngineering": "எந்திரவியல்",
    "dash.demandUp": "தேவை ↑",
    "dash.live": "நேரலை",
    "dash.indiaRiceExports": "இந்தியா அரிசி (HS 1006) ஆண்டு ஏற்றுமதி",
    "dash.realTime": "நேரடி",
    "dash.estimated": "மதிப்பீடு",
    "dash.marketAnalysisBased": "சந்தை பகுப்பாய்வை அடிப்படையாகக் கொண்டது",
    "dash.demandIndex": "தேவை குறியீடு",
    "dash.topExportMarkets": "முக்கிய ஏற்றுமதி சந்தைகள்",
    "dash.opportunityScores": "வாய்ப்பு மதிப்பெண்கள்",
    "dash.scoreLabel": "மதிப்பெண்",
    "dash.requiredDocuments": "தேவையான ஆவணங்கள்",
    "dash.potentialBuyers": "சாத்தியமான வாங்குநர்கள்",
    "dash.estimatedProfit": "மதிப்பிடப்பட்ட லாபம்",
    "dash.impactTitle": "ExportReady தாக்கம்",
    "dash.impactSubtitle": "இந்த தளம் இந்திய MSMEகளுக்கு ஏன் முக்கியம்",
    "dash.impactStat1": "63 மில்லியன்",
    "dash.impactDesc1": "இந்தியாவில் ஏற்றுமதிக்கு தகுதியான MSMEகள்",
    "dash.impactStat2": "மட்டும் 1.8%",
    "dash.impactDesc2": "இன்றே உண்மையில் ஏற்றுமதி செய்கின்றனர் — பெரிய வாய்ப்பு",
    "dash.impactStat3": "₹4.2L/ஆண்டு",
    "dash.impactDesc3": "தவறான HS குறியீடுகளால் சராசரி MSME இழப்பு",
    "dash.impactStat4": "70% குறைவு",
    "dash.impactDesc4": "ExportReady உடன் இணக்கம் பிழைகள்",
    "dash.footer": "என்டர்பிரைஸ் பாதுகாப்பு · உலகளாவிய இணக்கம் · நேரடி AI பகுப்பாய்வு · தரவு: UN Comtrade 2023",

    // ExportReadiness
    "readiness.title": "ஏற்றுமதி தயார்நிலை மதிப்பெண்",
    "readiness.stepsComplete": "{completed} / {total} படிகள் முடிந்தது",
    "readiness.nextStep": "அடுத்த தேவையான படி",
    "readiness.step": "படி",
    "readiness.whyMatters": "இது ஏன் முக்கியம்:",
    "readiness.markDone": "முடிந்ததாக குறி",
    "readiness.ready": "தயார்",
    "readiness.markComplete": "முழுமை என குறிக்கவும்",
    "readiness.markIncomplete": "முழுமையல்ல என குறிக்கவும்",
    "readiness.completed": "முடிந்தது",
    "readiness.points": "மதிப்பெண்கள்",
    "readiness.allComplete": "அனைத்து படிகளும் நிறைவு!",
    "readiness.allCompleteDesc": "உங்கள் ஏற்றுமதி பயணம் முழுவதும் அமைக்கப்பட்டுள்ளது.",
    "readiness.journeyTitle": "ஏற்றுமதி பயணம் — முதல் ஏற்றுமதிக்கு 5 படிகள்",
    "readiness.undo": "செயல்தவிர்",
    "readiness.auditTitle": "விரிவான இணக்க ஆய்வு",
    "readiness.completeTo": "இவற்றை நிறைவு செய்து அடையுங்கள்",
    "readiness.level.exportReady": "ஏற்றுமதிக்கு தயார் ✓",
    "readiness.level.almostReady": "கிட்டத்தட்ட தயார்",
    "readiness.level.gettingStarted": "தொடங்குகிறீர்கள்",
    "readiness.level.justBeginning": "இப்போதுதான் தொடக்கம்",
    "readiness.journey.iec.label": "IEC சான்றிதழை பதிவேற்றவும்",
    "readiness.journey.iec.why": "IEC (இறக்குமதி ஏற்றுமதி குறியீடு) இந்தியாவிலிருந்து சட்டப்படி ஏற்றுமதிக்கு கட்டாயம். DGFT மூலம் வழங்கப்படுகிறது.",
    "readiness.journey.iec.action": "சான்றிதழை பதிவேற்றவும்",
    "readiness.journey.product.label": "தயாரிப்பு விவரங்களை சேர்க்கவும்",
    "readiness.journey.product.why": "HS குறியீடு, விவரங்கள், விலை உள்ளிட்ட உங்கள் தயாரிப்பை பட்டியலிட்டு ஏற்றுமதி செயல்முறையை தொடங்குங்கள்.",
    "readiness.journey.product.action": "தயாரிப்பு சேர்க்கவும்",
    "readiness.journey.compliance.label": "இணக்கச் சரிபார்ப்பு இயக்கவும்",
    "readiness.journey.compliance.why": "உங்கள் இலக்கு சந்தைக்கான விதிமுறைகள், சான்றிதழ்கள், லேபிளிங் விதிகளை சரிபார்க்கவும்.",
    "readiness.journey.compliance.action": "இணக்கத்தை சரிபார்க்கவும்",
    "readiness.journey.market.label": "இலக்கு சந்தையை தேர்வு செய்யவும்",
    "readiness.journey.market.why": "AI கருத்துகளால் உங்கள் தயாரிப்புக்கான சிறந்த ஏற்றுமதி இடங்களையும் தேவைசெய்யும் வாங்குநர்களையும் கண்டறியவும்.",
    "readiness.journey.market.action": "சந்தைகளை ஆராயவும்",
    "readiness.journey.profit.label": "ஏற்றுமதி லாபம் கணக்கிடவும்",
    "readiness.journey.profit.why": "FOB விலை, சுங்கக் கட்டணங்கள், மார்ஜின்கள் மற்றும் மொத்த லாப திறனை சிமுலேட் செய்யவும்.",
    "readiness.journey.profit.action": "லாபம் சிமுலேட் செய்யவும்",
    "readiness.audit.iec.label": "IEC பதிவு",
    "readiness.audit.iec.detail": "DGFT போர்டலில் இருந்து இறக்குமதி ஏற்றுமதி குறியீடு",
    "readiness.audit.product.label": "தளத்தில் தயாரிப்பு பட்டியலிடப்பட்டது",
    "readiness.audit.product.detail": "குறைந்தது ஒரு தயாரிப்பு அமைக்கப்பட்டது",
    "readiness.audit.apeda.label": "APEDA / RCMC பதிவு",
    "readiness.audit.apeda.detail": "விவசாய மற்றும் செயல்படுத்தப்பட்ட உணவு ஏற்றுமதிக்கு தேவை",
    "readiness.audit.quality.label": "தர சான்றிதழ்",
    "readiness.audit.quality.detail": "பொருந்தினால் BIS / ISO / FSSAI / WHO-GMP",
    "readiness.audit.buyers.label": "வாங்குநர் தொடர்புகள் கண்டறியப்பட்டன",
    "readiness.audit.buyers.detail": "குறைந்தது 3 சரிபார்க்கப்பட்ட சர்வதேச வாங்குநர்கள்",
    "readiness.audit.bank.label": "ஏற்றுமதி வங்கி கணக்கு (EEFC)",
    "readiness.audit.bank.detail": "எக்சேஞ்ச் எர்னர்ஸ் வெளிநாட்டு நாணய கணக்கு",

    // Profile
    "profile.exportPassport": "ஏற்றுமதி கடவுச்சீட்டு",
    "profile.profileComplete": "சுயவிவரம் முழுமையானது",
    "profile.businessDetails": "வணிக விவரங்கள்",
    "profile.edit": "திருத்து",
    "profile.save": "சேமி",
    "profile.cancel": "ரத்துசெய்",
    "profile.experienceLevel": "ஏற்றுமதி அனுபவ நிலை",
    "profile.readinessProgress": "தயார்நிலை மதிப்பெண் முன்னேற்றம்",
    "profile.exportProducts": "ஏற்றுமதி பொருட்கள்",
    "profile.addProduct": "+ பொருள் சேர்க்கவும்",
    "profile.targetCountries": "இலக்கு நாடுகள்",
    "profile.exploreMore": "மேலும் ஆராயுங்கள் →",
    "profile.viewReadiness": "தயார்நிலை காண்க →",
    "profile.since": "முதல்",
    "profile.beginner": "தொடக்கநிலை",
    "profile.active": "செயலில்",
    "profile.pro": "புரொ",
    "profile.beginnerDesc": "ஏற்றுமதியில் புதியவர்",
    "profile.activeDesc": "1–3 ஏற்றுமதி/ஆண்டு",
    "profile.proDesc": "தொடர் ஏற்றுமதியாளர்",
    "profile.current": "தற்போதைய",
    "profile.demandIndex": "தேவை குறியீடு",
    "profile.exporter": "ஏற்றுமதியாளர்",
    "profile.iec": "IEC",
    "profile.gst": "GST",
    "profile.type": "வகை",
    "profile.exportingSince": "இருந்து ஏற்றுமதி",
    "profile.notSet": "அமைக்கப்படவில்லை",
    "profile.company": "நிறுவனம்",
    "profile.businessType": "வணிக வகை",
    "profile.city": "நகரம்",
    "profile.state": "மாநிலம்",
    "profile.iecNumber": "IEC எண்",
    "profile.gstNumber": "GST எண்",
    "profile.email": "மின்னஞ்சல்",
    "profile.phone": "தொலைபேசி",
    "profile.website": "இணையதளம்",
    "profile.hsCode": "HS குறியீடு",
    "profile.statusActive": "செயலில்",
    "profile.statusDraft": "வரைவு",

    // AccountSettings
    "settings.title": "கணக்கு அமைப்புகள்",
    "settings.subtitle": "அறிவிப்புகள், ஒருங்கிணைப்புகள் மற்றும் விருப்பத்தேர்வுகள்.",
    "settings.saveChanges": "மாற்றங்களை சேமி",
    "settings.saved": "சேமிக்கப்பட்டது",
    "settings.notifPrefs": "அறிவிப்பு விருப்பத்தேர்வுகள்",
    "settings.notifPrefsDesc": "உங்கள் ஏற்றுமதிக்கு முக்கியமான மின்னஞ்சல் விழிப்பூட்டல்களை தேர்ந்தெடுக்கவும்.",
    "settings.complianceDeadlines": "இணக்க காலக்கெடுக்கள்",
    "settings.complianceDeadlinesSub": "IEC புதுப்பித்தல், RCMC காலாவதி, FSSAI விழிப்பூட்டல்கள்",
    "settings.marketAlerts": "சந்தை வாய்ப்பு விழிப்பூட்டல்கள்",
    "settings.marketAlertsSub": "தேவை அதிகரிப்பு, இலக்கு சந்தைகளில் கட்டண மாற்றங்கள்",
    "settings.docReadiness": "ஆவண தயார்நிலை",
    "settings.docReadinessSub": "உருவாக்கப்பட்ட ஆவணங்கள் பதிவிறக்கத்திற்கு தயாராகும்போது",
    "settings.weeklyDigest": "வாராந்திர சுருக்கம்",
    "settings.weeklyDigestSub": "உங்கள் ஏற்றுமதி தயார்நிலை மற்றும் செயல்பாட்டின் சுருக்கம்",
    "settings.langCurrency": "மொழி மற்றும் நாணயம்",
    "settings.langCurrencyDesc": "உங்கள் பிராந்தியத்திற்கான காட்சி விருப்பங்கள்.",
    "settings.language": "மொழி",
    "settings.currency": "நாணயம்",
    "settings.timezone": "நேர மண்டலம்",
    "settings.dataPrivacy": "தரவு மற்றும் தனியுரிமை",
    "settings.exportData": "என் தரவை ஏற்றுமதி செய்க",
    "settings.integrations": "இணைக்கப்பட்ட ஒருங்கிணைப்புகள்",
    "settings.integrationsDesc": "அரசு போர்டல்கள் மற்றும் லாஜிஸ்டிக்ஸ் கூட்டாளர்களை இணைக்கவும்.",
    "settings.connect": "இணை",
    "settings.disconnect": "துண்டி",
    "settings.plan": "சந்தா திட்டம்",
    "settings.planDesc": "உங்கள் ExportReady திட்டத்தை நிர்வகிக்கவும்.",
    "settings.currentPlan": "தற்போதைய திட்டம்",
    "settings.includedFeatures": "சேர்க்கப்பட்ட அம்சங்கள்",
    "settings.upgradePlan": "திட்டத்தை மேம்படுத்து",
    "settings.viewInvoices": "விலைப்பட்டியல்கள் காண்க",
    "settings.cancelPlan": "திட்டத்தை ரத்துசெய்",
  },
};

const LanguageContext = createContext(null);

export function LanguageProvider({ children }) {
  const [language, setLanguageState] = useState(
    () => localStorage.getItem("exportready_lang") || "en"
  );

  const setLanguage = (lang) => {
    localStorage.setItem("exportready_lang", lang);
    setLanguageState(lang);
  };

  const t = (key) => {
    return translations[language]?.[key] ?? translations["en"][key] ?? key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}

